services:
  - type: web
    name: cosmotalker-api
    runtime: python
    repo: https://github.com/bhuvanesh-m-dev/cosmotalker/tree/main/api/get
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
